<?php
class OrdenServicio extends Model {
 public function all():array{return $this->db->query('SELECT o.*,e.codigo_equipo,e.nombre_equipo,CONCAT(u.nombres," ",u.apellidos) tecnico,es.nombre_estado FROM ordenes_servicio o JOIN equipos e ON e.id_equipo=o.id_equipo LEFT JOIN tecnicos t ON t.id_tecnico=o.id_tecnico LEFT JOIN usuarios u ON u.id_usuario=t.id_usuario JOIN estados_orden es ON es.id_estado=o.id_estado ORDER BY o.id_orden DESC')->fetchAll();}
 public function options():array{return ['equipos'=>$this->db->query('SELECT id_equipo,CONCAT(codigo_equipo," - ",nombre_equipo) nombre FROM equipos ORDER BY nombre_equipo')->fetchAll(),'tecnicos'=>$this->db->query('SELECT t.id_tecnico,CONCAT(u.nombres," ",u.apellidos) nombre FROM tecnicos t JOIN usuarios u ON u.id_usuario=t.id_usuario WHERE t.estado=1')->fetchAll(),'estados'=>$this->db->query('SELECT * FROM estados_orden ORDER BY orden_visual')->fetchAll()];}
 public function create(array $d):void{$q=$this->db->prepare('INSERT INTO ordenes_servicio(id_equipo,id_tecnico,id_estado,tipo_mantenimiento,prioridad,fecha_solicitud,fecha_programada,descripcion_falla,costo_mano_obra,costo_total) VALUES(?,?,?,?,?,NOW(),?,?,?,?,?)');$c=(float)($d['costo_mano_obra']??0);$q->execute([(int)$d['id_equipo'],(int)$d['id_tecnico'],(int)$d['id_estado'],$d['tipo_mantenimiento'],$d['prioridad'],$d['fecha_programada']?:null,trim($d['descripcion_falla']),$c,$c]);}
 public function find(int $id):?array{$q=$this->db->prepare('SELECT o.*,e.nombre_equipo,es.nombre_estado FROM ordenes_servicio o JOIN equipos e ON e.id_equipo=o.id_equipo JOIN estados_orden es ON es.id_estado=o.id_estado WHERE id_orden=?');$q->execute([$id]);$o=$q->fetch();if($o){$q=$this->db->prepare('SELECT d.*,r.nombre_repuesto FROM detalle_orden d LEFT JOIN repuestos r ON r.id_repuesto=d.id_repuesto WHERE id_orden=?');$q->execute([$id]);$o['detalles']=$q->fetchAll();}return $o?:null;}
 public function updateWork(int $id,array $d):void{$q=$this->db->prepare('UPDATE ordenes_servicio SET id_estado=?,diagnostico=?,solucion=?,observaciones=?,fecha_inicio=COALESCE(fecha_inicio,NOW()),fecha_cierre=CASE WHEN ?=5 THEN NOW() ELSE fecha_cierre END WHERE id_orden=?');$q->execute([(int)$d['id_estado'],trim($d['diagnostico']),trim($d['solucion']),trim($d['observaciones']),(int)$d['id_estado'],$id]);}
}

