DROP DATABASE IF EXISTS bd_tw_maintflow;
CREATE DATABASE bd_tw_maintflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bd_tw_maintflow;
CREATE TABLE roles(id_rol INT AUTO_INCREMENT PRIMARY KEY,nombre_rol VARCHAR(30) UNIQUE NOT NULL,descripcion VARCHAR(150),estado TINYINT DEFAULT 1);
CREATE TABLE usuarios(id_usuario INT AUTO_INCREMENT PRIMARY KEY,id_rol INT NOT NULL,username VARCHAR(50) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,nombres VARCHAR(80) NOT NULL,apellidos VARCHAR(80) NOT NULL,correo VARCHAR(120),estado TINYINT DEFAULT 1,fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(id_rol) REFERENCES roles(id_rol));
CREATE TABLE clientes(id_cliente INT AUTO_INCREMENT PRIMARY KEY,razon_social VARCHAR(150) NOT NULL,ruc CHAR(11) UNIQUE NOT NULL,contacto VARCHAR(120),telefono VARCHAR(20),correo VARCHAR(120),direccion VARCHAR(180),estado TINYINT DEFAULT 1,fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sedes(id_sede INT AUTO_INCREMENT PRIMARY KEY,id_cliente INT NOT NULL,nombre_sede VARCHAR(120) NOT NULL,direccion VARCHAR(180),distrito VARCHAR(80),provincia VARCHAR(80),departamento VARCHAR(80),estado TINYINT DEFAULT 1,FOREIGN KEY(id_cliente) REFERENCES clientes(id_cliente));
CREATE TABLE categorias_equipo(id_categoria INT AUTO_INCREMENT PRIMARY KEY,nombre_categoria VARCHAR(100) UNIQUE NOT NULL,descripcion VARCHAR(180),estado TINYINT DEFAULT 1);
CREATE TABLE equipos(id_equipo INT AUTO_INCREMENT PRIMARY KEY,id_sede INT NOT NULL,id_categoria INT NOT NULL,codigo_equipo VARCHAR(30) UNIQUE NOT NULL,nombre_equipo VARCHAR(120) NOT NULL,marca VARCHAR(80),modelo VARCHAR(80),numero_serie VARCHAR(80),fecha_adquisicion DATE,estado_operativo VARCHAR(30) DEFAULT 'Operativo',observaciones TEXT,FOREIGN KEY(id_sede) REFERENCES sedes(id_sede),FOREIGN KEY(id_categoria) REFERENCES categorias_equipo(id_categoria));
CREATE TABLE tecnicos(id_tecnico INT AUTO_INCREMENT PRIMARY KEY,id_usuario INT UNIQUE NOT NULL,especialidad VARCHAR(100),telefono VARCHAR(20),fecha_ingreso DATE,estado TINYINT DEFAULT 1,FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario));
CREATE TABLE estados_orden(id_estado INT AUTO_INCREMENT PRIMARY KEY,nombre_estado VARCHAR(40) UNIQUE NOT NULL,descripcion VARCHAR(150),orden_visual INT NOT NULL);
CREATE TABLE ordenes_servicio(id_orden INT AUTO_INCREMENT PRIMARY KEY,id_equipo INT NOT NULL,id_tecnico INT,id_estado INT NOT NULL,tipo_mantenimiento ENUM('Preventivo','Correctivo') NOT NULL,prioridad ENUM('Baja','Media','Alta','Crítica') DEFAULT 'Media',fecha_solicitud DATETIME DEFAULT CURRENT_TIMESTAMP,fecha_programada DATE,fecha_inicio DATETIME,fecha_cierre DATETIME,descripcion_falla TEXT NOT NULL,diagnostico TEXT,solucion TEXT,observaciones TEXT,costo_mano_obra DECIMAL(10,2) DEFAULT 0,costo_total DECIMAL(10,2) DEFAULT 0,FOREIGN KEY(id_equipo) REFERENCES equipos(id_equipo),FOREIGN KEY(id_tecnico) REFERENCES tecnicos(id_tecnico),FOREIGN KEY(id_estado) REFERENCES estados_orden(id_estado));
CREATE TABLE repuestos(id_repuesto INT AUTO_INCREMENT PRIMARY KEY,codigo_repuesto VARCHAR(30) UNIQUE NOT NULL,nombre_repuesto VARCHAR(120) NOT NULL,descripcion VARCHAR(180),unidad_medida VARCHAR(30),stock_actual DECIMAL(10,2) DEFAULT 0,stock_minimo DECIMAL(10,2) DEFAULT 0,precio_unitario DECIMAL(10,2) DEFAULT 0,estado TINYINT DEFAULT 1);
CREATE TABLE detalle_orden(id_detalle INT AUTO_INCREMENT PRIMARY KEY,id_orden INT NOT NULL,id_repuesto INT NULL,descripcion_actividad VARCHAR(255) NOT NULL,cantidad DECIMAL(10,2) DEFAULT 0,precio_unitario DECIMAL(10,2) DEFAULT 0,subtotal DECIMAL(10,2) GENERATED ALWAYS AS(cantidad*precio_unitario) STORED,FOREIGN KEY(id_orden) REFERENCES ordenes_servicio(id_orden),FOREIGN KEY(id_repuesto) REFERENCES repuestos(id_repuesto));
CREATE TABLE movimientos_repuesto(id_movimiento INT AUTO_INCREMENT PRIMARY KEY,id_repuesto INT NOT NULL,id_usuario INT NOT NULL,tipo_movimiento ENUM('Entrada','Salida','Ajuste') NOT NULL,cantidad DECIMAL(10,2) NOT NULL,motivo VARCHAR(180),fecha_movimiento DATETIME DEFAULT CURRENT_TIMESTAMP,referencia VARCHAR(80),FOREIGN KEY(id_repuesto) REFERENCES repuestos(id_repuesto),FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario));
INSERT INTO roles VALUES (1,'administrador','Acceso total',1),(2,'recepcion','Registro y consulta',1),(3,'tecnico','Gestión técnica',1);
INSERT INTO usuarios(id_rol,username,password_hash,nombres,apellidos,correo) VALUES
(1,'admin','$2y$10$ban4/C9Mp0X7Cql4TZTARetgNGHvOXsPVvKsPCh3kqV12GEgviR5m','Ana','Torres','admin@demo.pe'),
(2,'recepcion','$2y$10$ztZV6F6otDlm66pe1ExBu.p1l1CxftFLsP9vRxoKbTGHDYVX778Se','Rosa','Mendoza','recepcion@demo.pe'),
(3,'tecnico','$2y$10$DD9/DnMBpLcC.xX/4sSNGOGm.aiMVCE/tIdz01sfVnw/T5DDFb4Ja','Luis','Paredes','tecnico@demo.pe'),
(3,'tecnico2','$2y$10$DD9/DnMBpLcC.xX/4sSNGOGm.aiMVCE/tIdz01sfVnw/T5DDFb4Ja','Mario','Quispe','mario@demo.pe'),
(3,'tecnico3','$2y$10$DD9/DnMBpLcC.xX/4sSNGOGm.aiMVCE/tIdz01sfVnw/T5DDFb4Ja','Carla','Ríos','carla@demo.pe');
INSERT INTO clientes(razon_social,ruc,contacto,telefono,correo,direccion) VALUES ('Industrias Pacífico SAC','20100000001','Julio Peña','999111001','contacto1@demo.pe','Callao'),('TecnoSur SA','20100000002','Mila Rojas','999111002','contacto2@demo.pe','Lima'),('Aceros Andinos SAC','20100000003','Raúl Soto','999111003','contacto3@demo.pe','Ate'),('Logística Norte EIRL','20100000004','Iris León','999111004','contacto4@demo.pe','Los Olivos'),('Alimentos del Puerto SA','20100000005','Pablo Vera','999111005','contacto5@demo.pe','Ventanilla');
INSERT INTO sedes(id_cliente,nombre_sede,direccion,distrito,provincia,departamento) VALUES (1,'Planta Callao','Av. Industrial 101','Callao','Callao','Callao'),(1,'Almacén 2','Av. Néstor 202','Callao','Callao','Callao'),(2,'Sede Central','Av. Sur 303','Miraflores','Lima','Lima'),(2,'Taller','Av. Taller 40','Chorrillos','Lima','Lima'),(3,'Planta Ate','Av. Separadora 50','Ate','Lima','Lima'),(4,'Centro Norte','Av. Próceres 60','Los Olivos','Lima','Lima'),(5,'Planta 1','Av. Gambetta 70','Ventanilla','Callao','Callao'),(5,'Frigorífico','Av. Gambetta 71','Ventanilla','Callao','Callao');
INSERT INTO categorias_equipo(nombre_categoria,descripcion) VALUES ('Bombas','Bombas industriales'),('Motores','Motores eléctricos'),('Compresores','Aire comprimido'),('Tableros','Tableros eléctricos'),('HVAC','Climatización'),('Generadores','Generación eléctrica');
INSERT INTO equipos(id_sede,id_categoria,codigo_equipo,nombre_equipo,marca,modelo,numero_serie,fecha_adquisicion,estado_operativo) VALUES (1,1,'EQ-001','Bomba centrífuga 1','Grundfos','CR-10','S001','2022-01-10','Operativo'),(1,2,'EQ-002','Motor principal','Siemens','M50','S002','2021-02-15','Operativo'),(2,3,'EQ-003','Compresor A','Atlas','GA11','S003','2020-05-11','En mantenimiento'),(3,4,'EQ-004','Tablero general','Schneider','TG2','S004','2023-04-03','Operativo'),(4,5,'EQ-005','Chiller','Carrier','C30','S005','2022-07-21','Operativo'),(5,6,'EQ-006','Generador','Caterpillar','G80','S006','2019-08-10','Operativo'),(6,1,'EQ-007','Bomba respaldo','KSB','K20','S007','2021-09-12','Operativo'),(7,2,'EQ-008','Motor faja','WEG','W12','S008','2020-10-13','Detenido'),(8,3,'EQ-009','Compresor frío','Danfoss','D4','S009','2023-11-14','Operativo'),(3,4,'EQ-010','Tablero UPS','ABB','U5','S010','2024-01-15','Operativo'),(5,5,'EQ-011','Extractor','LG','E2','S011','2022-03-12','Operativo'),(7,6,'EQ-012','Grupo electrógeno','Cummins','C90','S012','2020-06-16','Operativo');
INSERT INTO tecnicos(id_usuario,especialidad,telefono,fecha_ingreso) VALUES (3,'Mecánica','988001001','2023-01-10'),(4,'Electricidad','988001002','2022-04-12'),(5,'Refrigeración','988001003','2024-02-01'),(1,'Supervisión','988001004','2021-06-01');
INSERT INTO estados_orden VALUES (1,'Pendiente','Registrada',1),(2,'Asignada','Técnico asignado',2),(3,'En proceso','Trabajo iniciado',3),(4,'En espera','Espera de recurso',4),(5,'Cerrada','Trabajo concluido',5);
INSERT INTO repuestos(codigo_repuesto,nombre_repuesto,descripcion,unidad_medida,stock_actual,stock_minimo,precio_unitario) VALUES ('RP-001','Rodamiento 6204','Rodamiento sellado','unidad',18,5,25),('RP-002','Aceite ISO 46','Lubricante','litro',30,10,18),('RP-003','Correa A42','Correa industrial','unidad',4,5,35),('RP-004','Contactor 32A','Contactor','unidad',8,3,80),('RP-005','Filtro de aire','Filtro','unidad',3,4,45),('RP-006','Fusible 20A','Fusible','unidad',25,8,6),('RP-007','Sello mecánico','Sello','unidad',6,2,120),('RP-008','Refrigerante R410','Gas','kg',12,5,55),('RP-009','Cable THW','Cable','metro',80,20,4),('RP-010','Sensor temperatura','Sensor','unidad',2,3,95);
INSERT INTO ordenes_servicio(id_equipo,id_tecnico,id_estado,tipo_mantenimiento,prioridad,fecha_programada,descripcion_falla,costo_mano_obra,costo_total) VALUES (1,1,5,'Preventivo','Media','2026-06-01','Mantenimiento periódico',120,163),(2,2,3,'Correctivo','Alta','2026-07-10','Vibración excesiva',180,205),(3,1,2,'Preventivo','Media','2026-07-12','Inspección 500 horas',100,100),(4,2,1,'Correctivo','Crítica','2026-07-11','Disparo intermitente',150,150),(5,3,3,'Correctivo','Alta','2026-07-11','No enfría',200,255),(6,4,2,'Preventivo','Baja','2026-07-15','Prueba mensual',90,90),(7,1,1,'Correctivo','Media','2026-07-16','Fuga menor',130,130),(8,2,4,'Correctivo','Alta','2026-07-09','Motor detenido',160,240),(9,3,5,'Preventivo','Media','2026-06-20','Limpieza y prueba',110,165),(10,2,1,'Preventivo','Baja','2026-07-18','Revisión semestral',80,80);
INSERT INTO detalle_orden(id_orden,id_repuesto,descripcion_actividad,cantidad,precio_unitario) VALUES (1,1,'Cambio de rodamiento',1,25),(1,2,'Lubricación',1,18),(2,1,'Alineación y cambio',1,25),(3,NULL,'Inspección general',0,0),(4,6,'Cambio de fusible',2,6),(5,8,'Recarga refrigerante',1,55),(6,NULL,'Prueba en vacío',0,0),(7,7,'Cambio de sello',1,120),(8,4,'Cambio contactor',1,80),(9,8,'Recarga',1,55),(10,NULL,'Termografía',0,0),(2,NULL,'Medición vibración',0,0),(4,9,'Recableado',5,4),(5,10,'Prueba de sensor',1,95),(8,3,'Cambio de correa',1,35);
INSERT INTO movimientos_repuesto(id_repuesto,id_usuario,tipo_movimiento,cantidad,motivo,referencia) VALUES (1,1,'Entrada',20,'Compra','OC-001'),(2,1,'Entrada',35,'Compra','OC-002'),(3,1,'Entrada',5,'Compra','OC-003'),(4,1,'Entrada',10,'Compra','OC-004'),(5,1,'Entrada',5,'Compra','OC-005'),(6,1,'Entrada',30,'Compra','OC-006'),(7,1,'Entrada',8,'Compra','OC-007'),(8,1,'Entrada',15,'Compra','OC-008'),(9,1,'Entrada',100,'Compra','OC-009'),(10,1,'Entrada',4,'Compra','OC-010'),(1,3,'Salida',2,'Orden','OS-001'),(2,3,'Salida',5,'Orden','OS-001'),(4,4,'Salida',2,'Orden','OS-008'),(8,5,'Salida',3,'Orden','OS-009'),(9,4,'Salida',20,'Orden','OS-004');
DELIMITER $$
CREATE TRIGGER tr_detalle_stock AFTER INSERT ON detalle_orden FOR EACH ROW BEGIN IF NEW.id_repuesto IS NOT NULL AND NEW.cantidad>0 THEN UPDATE repuestos SET stock_actual=stock_actual-NEW.cantidad WHERE id_repuesto=NEW.id_repuesto; UPDATE ordenes_servicio SET costo_total=costo_mano_obra+(SELECT COALESCE(SUM(subtotal),0) FROM detalle_orden WHERE id_orden=NEW.id_orden) WHERE id_orden=NEW.id_orden; END IF; END$$
CREATE PROCEDURE sp_cerrar_orden(IN p_id INT) BEGIN UPDATE ordenes_servicio SET id_estado=5,fecha_cierre=NOW() WHERE id_orden=p_id; END$$
CREATE FUNCTION fn_total_orden(p_id INT) RETURNS DECIMAL(10,2) DETERMINISTIC BEGIN DECLARE t DECIMAL(10,2); SELECT costo_mano_obra+COALESCE((SELECT SUM(subtotal) FROM detalle_orden WHERE id_orden=p_id),0) INTO t FROM ordenes_servicio WHERE id_orden=p_id; RETURN t; END$$
DELIMITER ;

